import { useEffect, useState } from 'react'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/react'
import { Button, ContactForm, CookieBanner, Footer, Header, Panel, ScrollToTop, StatusBar } from './components'
import { usePath } from './router'

const offers = [
  { tier: '01 · Starter', title: 'Agent Starter', desc: 'Osobní AI asistent pro jednotlivce — rychlé nasazení, okamžitý přínos.', price: '3 000–5 000 Kč', monthly: '+ 300–500 Kč / měsíc', items: ['Instalace a konfigurace jednoho agenta', 'Napojení na kalendář a Telegram / e-mail', 'Základní denní přehledy a připomínky', 'Zaškolení, jak s agentem pracovat'] },
  { tier: '02 · Pro', title: 'Agent Pro', desc: 'Pro pokročilé jednotlivce a mikrofirmy s víc nástroji a vlastní logikou.', price: '8 000–15 000 Kč', monthly: '+ 600–1 000 Kč / měsíc', featured: true, items: ['Více propojených nástrojů (Drive, Todoist, CRM…)', 'Vlastní automatizace a „skills“ na míru', 'Pravidelné automatické briefingy', 'Nastavení bezpečnosti a přístupových práv'] },
  { tier: '03 · Business', title: 'Agent Business', desc: 'Firemní nasazení se self-hosted infrastrukturou a bezpečnostním auditem.', price: 'od 25 000 Kč', monthly: '+ od 2 000 Kč / měsíc', vision: true, items: ['Analýza procesů a návrh architektury', 'Self-hosted infrastruktura (data zůstávají u vás)', 'Napojení na interní firemní systémy', 'Bezpečnostní audit a školení týmu'] }
]
const process = [['01', 'Konzultace', 'Probereme, co má smysl automatizovat a jaká data jsou v sázce.'], ['02', 'Návrh', 'Navrhnu architekturu, rozsah a bezpečnostní model nasazení.'], ['03', 'Nasazení', 'Agent se nastaví, propojí s vašimi nástroji a otestuje v provozu.'], ['04', 'Provoz', 'Průběžný monitoring, úpravy a měsíční přehled o chodu agenta.']]
const technology = [
  ['OpenClaw', 'Osobní i firemní agenti s dlouhodobým provozem', 'Vlastní self-hosted architektura, skill-file systém, MCP integrace', 'U většiny zakázek — Starter i Pro balíček'],
  ['n8n', 'Vizuální automatizace mezi nástroji', 'Rychlé propojení systémů bez psaní vlastní logiky', 'Když jde hlavně o „když se stane X, udělej Y“'],
  ['LangChain / CrewAI', 'Víceagentové systémy s dělbou rolí', 'Flexibilní orchestrace více specializovaných agentů', 'Komplexnější firemní nasazení (Business)'],
  ['Vlastní řešení', 'Velmi specifické firemní požadavky', 'Přesné zapadnutí do existující infrastruktury', 'Když žádný framework nesedí na míru']
]
const infrastructure = [
  ['Doporučeno', 'Self-hosted', 'Agent běží na vašem vlastním hardwaru — domácí NAS, firemní server nebo mini PC.', ['Data nikdy neopustí vaši síť', 'Jednorázová investice do hardwaru (pokud ho nemáte)', 'Vyžaduje minimální údržbu, kterou zajišťuji já']],
  ['Alternativa', 'Privátní VPS', 'Agent běží na pronajatém serveru (např. v EU datacentru), pokud nemáte vlastní hardware.', ['Rychlý start bez nákupu hardwaru', 'Data u prověřeného EU poskytovatele, ne u velkého Big Tech cloudu', 'Měsíční náklad na server navíc k paušálu']],
  ['Pro specifické případy', 'Hybridní', 'Citlivá data a logika na vašem serveru, výpočetně náročné úlohy externě.', ['Kombinuje kontrolu nad daty s výkonem cloudu', 'Vyžaduje pečlivější návrh architektury', 'Typicky u větších firemních nasazení']]
]
const costs = [
  ['Model podle úlohy, ne automaticky ten nejsilnější', 'Jednoduché úlohy jdou na levnější, rychlejší model. Náročnější úlohy na výkonnější model. Výběr modelu nikdy nenecháváme na automatickém routingu bez kontroly nákladů.'],
  ['Omezené kontextové okno', 'Agent nedostává při každém dotazu celou historii všeho — jen relevantní část. Méně vstupního textu znamená méně tokenů a nižší cenu za dotaz.'],
  ['Cachování opakovaných dotazů', 'Opakované systémové instrukce se cachují místo opakovaného přepočítávání, což u některých poskytovatelů výrazně snižuje cenu.'],
  ['Limity a alerty', 'Každé nasazení má nastavený měsíční strop útraty za API. Při blížícím se limitu dostaneme upozornění včas.'],
  ['Měsíční přehled', 'V rámci paušálu dostanete stručný report — kolik agent stál na provozu a proč, ne jen fakturu bez kontextu.']
]

function SectionHead({ eyebrow, title, children }) { return <div className="section-head"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{children && <p className="section-sub">{children}</p>}</div> }
function HomePage({ onOpenCookies }) { return <>
  <section className="hero no-border"><div className="wrap"><div className="eyebrow">Konfigurace & správa AI agentů</div><h1>Vlastní AI agenti,<br />které máte <em>pod kontrolou</em>.</h1><p className="lede">Navrhujeme, nasazujeme a spravujeme self-hosted AI asistenty pro jednotlivce i firmy — propojené s vašimi nástroji, bez posílání citlivých dat cizím cloudům.</p><div className="cta-row"><Button to="/#kontakt" primary eventName="Kliknout na konzultaci">Nezávazná konzultace</Button><Button to="/#sluzby" eventName="Zobrazit služby">Zobrazit služby</Button></div></div></section>
  <section id="pro-koho"><div className="wrap"><SectionHead eyebrow="Pro koho" title="Jednotlivci i firmy s citlivými daty" /><div className="grid-2"><div><h3>Jednotlivci</h3><p>Chcete osobního AI asistenta na e-maily, kalendář, plánování — ale nastavit a udržovat si ho sami nechcete nebo nemáte čas.</p></div><div><h3>Firmy</h3><p>Chcete využít AI agenty v provozu, ale data musí zůstat u vás — bez závislosti na cizích SaaS platformách a jejich politice zpracování dat.</p></div></div></div></section>
  <section id="sluzby"><div className="wrap"><SectionHead eyebrow="Nabídka" title="Tři úrovně nasazení">Cena se skládá ze vstupní implementace a nízkého měsíčního paušálu, který zahrnuje monitoring provozu a drobné úpravy.</SectionHead><div className="services">{offers.map((offer) => <Panel key={offer.title} className={`service ${offer.featured ? 'featured' : ''} ${offer.vision ? 'vision' : ''}`}>{offer.featured && <span className="badge">Nejčastější volba</span>}<div className="tier">{offer.tier}</div><h3>{offer.title}</h3><p className="desc">{offer.desc}</p><div className="price">{offer.price} <small>setup</small></div><div className="monthly">{offer.monthly}</div><ul>{offer.items.map((item) => <li key={item}>{item}</li>)}</ul>{offer.vision && <div className="vision-tag">Individuální nabídka</div>}</Panel>)}</div><p className="included-note"><b>Monitoring je součástí každé služby</b> — sledujeme, že agent běží správně a náklady na API zůstávají pod kontrolou, a jednou měsíčně dostanete stručný přehled.</p><div className="audit"><p><b>Nejste si jistí, kde začít?</b> Úvodní konzultace je vždy zdarma. Pokud máte agenta už nastaveného, nabízíme i samostatný placený bezpečnostní audit.</p><Button to="/#kontakt">Domluvit konzultaci</Button></div></div></section>
  <section id="proces"><div className="wrap"><SectionHead eyebrow="Jak to probíhá" title="Od konzultace po provoz" /><div className="process">{process.map(([number, title, text]) => <div className="step" key={number}><div className="num">{number}</div><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
  <section id="proc"><div className="wrap"><SectionHead eyebrow="Proč SecureAgents" title="Bezpečnost není dodatek, je to základ" /><div className="why-grid">{[['Self-hosted / vlastní infrastruktura', 'Data zůstávají u vás — na vašem NAS, VPS nebo serveru, ne roztroušená po cizích cloudech.'], ['Cybersecurity zázemí', 'Nasazení navrhujeme s ohledem na skutečná rizika — oprávnění, izolaci dat, zneužitelnost.'], ['Reálná provozní zkušenost', 'Agenty dlouhodobě provozujeme na vlastní infrastruktuře — víme, co se rozbije, dřív než se to stane vám.']].map(([title, text]) => <div className="why-item" key={title}><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
  <section id="scenare"><div className="wrap"><SectionHead eyebrow="Konkrétní využití" title="Kde agent ušetří čas už první týden">Nejde o obecný chatbot. Agent dostane přesně vymezené úkoly, nástroje a oprávnění.</SectionHead><div className="scenario-grid">{[['Ranní briefing', 'Každé ráno připraví přehled kalendáře, důležitých e-mailů, úkolů a rizik pro daný den.'], ['E-maily pod kontrolou', 'Vytřídí příchozí poštu, vytáhne úkoly a připraví návrhy odpovědí k vašemu schválení.'], ['Provozní přehledy', 'Propojí data z vybraných nástrojů do stručného pravidelného reportu místo ručního dohledávání.'], ['Bezpečné napojení systémů', 'Předá jen nezbytná data mezi kalendářem, úkoly, CRM nebo interními zdroji.']].map(([title, text]) => <div className="scenario-card panel" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div><p className="model-note">Modelové scénáře ukazují typické možnosti nasazení. Konkrétní rozsah vždy navrhneme podle vašich dat a procesů.</p></div></section>
  <section id="kontakt"><div className="wrap contact-wrap"><SectionHead eyebrow="Poptávka" title="Popište, co by měl agent převzít">Ozveme se s návrhem vhodného postupu a bezplatné úvodní konzultace.</SectionHead><ContactForm /></div></section>
  <Footer onOpenCookies={onOpenCookies} />
</> }

function HowItWorks({ onOpenCookies }) { return <>
  <section className="hero compact no-border"><div className="wrap"><div className="eyebrow">Pod pokličkou</div><h1>Přes co to stavíme a <em>co vás to bude stát.</em></h1><p className="lede">Žádná černá skříňka. Tady je popsané, jaký software agenty pohání, kde reálně běží data a jak se řídí náklady na provoz.</p></div></section>
  <section id="technologie"><div className="wrap"><SectionHead eyebrow="01 · Technologie" title="Nástroj volím podle úlohy, ne podle zvyku">Primárně stavím na OpenClaw, pro specifické případy ale sahám i po jiných frameworcích.</SectionHead><div className="stack-grid"><div className="head" /><div className="head mono">ÚČEL</div><div className="head mono">SILNÁ STRÁNKA</div><div className="head mono">KDY TO POUŽÍVÁM</div>{technology.flatMap(([name, purpose, strength, when], index) => [<div key={`${name}-name`}><div className={`tool ${index === 0 ? 'primary' : ''}`}>{name}</div>{index === 0 && <span className="tag-default">Výchozí volba</span>}</div>, <div key={`${name}-purpose`} className="role">{purpose}</div>, <div key={`${name}-strength`} className="role">{strength}</div>, <div key={`${name}-when`} className="role">{when}</div>])}</div><div className="callout"><b>Proč ne vždy OpenClaw?</b> Cíl je vyřešit váš problém, ne prosazovat jeden nástroj. Volba se odvíjí od toho, co potřebujete automatizovat a jak moc se má systém dát přehledně kontrolovat.</div></div></section>
  <section id="infrastruktura"><div className="wrap"><SectionHead eyebrow="02 · Infrastruktura" title="Kde to celé běží">Doporučuju self-hosted řešení, protože dává nejvyšší kontrolu nad daty. Podle rozpočtu a technického zázemí jde postavit i jinak.</SectionHead><div className="infra-grid">{infrastructure.map(([tier, title, text, items], index) => <Panel key={title} className={`infra-card ${index === 0 ? 'recommended' : ''}`}><div className="tier">{tier}</div><h3>{title}</h3><p>{text}</p><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></Panel>)}</div><p className="callout"><b>V každém případě</b> platí, že samotný AI model běží u externího poskytovatele — jde o krátké jednotlivé dotazy, ne o průběžný přístup k vašim datům. Data, historie a logika agenta zůstávají na infrastruktuře, kterou pro vás navrhneme.</p></div></section>
  <section id="naklady"><div className="wrap"><SectionHead eyebrow="03 · Náklady na tokeny" title="Jak se platí AI model a jak náklady držím dole">Každý dotaz na AI model stojí peníze podle množství zpracovaného textu — tzv. tokenů. Takhle to řídím:</SectionHead><div className="cost-flow">{costs.map(([title, text], index) => <div className="cost-row" key={title}><div className="marker">{String(index + 1).padStart(2, '0')}</div><div><h4>{title}</h4><p>{text}</p></div></div>)}</div><div className="callout"><b>Reálná zkušenost, ne teorie.</b> Náklady na provoz nastavujeme jako prioritu už od návrhu, ne až po problému.</div></div></section>
  <Footer technical onOpenCookies={onOpenCookies} />
</> }

function PrivacyPage({ onOpenCookies }) { return <><section className="hero compact no-border"><div className="wrap"><div className="eyebrow">Soukromí</div><h1>Ochrana osobních údajů a <em>cookies</em>.</h1><p className="lede">Přehledně vysvětlujeme, jak na webu SecureAgents pracujeme s údaji návštěvníků.</p></div></section><section><div className="wrap privacy-page"><div className="privacy-card"><h2>Správce údajů</h2><p>Správcem osobních údajů je Adam Pospíšek, projekt SecureAgents. Pro dotazy k soukromí nás kontaktujte na <a href="mailto:info@secureagents.cz">info@secureagents.cz</a>.</p></div><div className="privacy-card"><h2>Jaké údaje zpracováváme</h2><p>Při běžné návštěvě webu nezadáváte žádný kontaktní formulář. Pokud nám napíšete e-mail, zpracujeme údaje uvedené ve zprávě pouze pro vyřízení vašeho dotazu a navazující komunikaci.</p></div><div className="privacy-card"><h2>Cookies a místní úložiště</h2><p>Web si do místního úložiště prohlížeče ukládá vaši volbu ohledně analytiky. Tato nezbytná položka se jmenuje <code>secureagents_cookie_consent</code> a slouží pouze k tomu, aby se lišta nezobrazovala při každé návštěvě.</p><p>Analytická měření Vercel Analytics a Speed Insights spouštíme až po vašem souhlasu. Pomáhají nám sledovat návštěvnost a technický výkon webu.</p><button className="btn" onClick={onOpenCookies}>Změnit nastavení cookies</button></div><div className="privacy-card"><h2>Vaše práva</h2><p>Máte právo požádat o přístup k osobním údajům, jejich opravu, výmaz, omezení zpracování nebo vznést námitku. Žádost pošlete na výše uvedený e-mail.</p><p>Pokud se domníváte, že s údaji nenakládáme správně, můžete se obrátit na Úřad pro ochranu osobních údajů.</p></div><div className="privacy-card"><h2>Aktualizace zásad</h2><p>Tyto zásady můžeme upravit, pokud se změní způsob fungování webu nebo používané služby. Poslední aktualizace: 9. srpna 2026.</p></div></div></section><Footer onOpenCookies={onOpenCookies} /></> }

function useRevealAnimations(path) { useEffect(() => { const targets = [...document.querySelectorAll('.hero .wrap, .section-head, .grid-2, .panel, .step, .why-item, .callout, .audit, footer .wrap, .privacy-card')]; const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches; targets.forEach((element) => element.classList.add('reveal')); if (reduced) { targets.forEach((element) => element.classList.add('is-visible')); return undefined } document.documentElement.classList.add('motion-ready'); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target) } }), { threshold: 0.12 }); targets.forEach((element) => observer.observe(element)); return () => { observer.disconnect(); document.documentElement.classList.remove('motion-ready') } }, [path]) }

function usePageMetadata(path) { useEffect(() => { const pages = { '/': { title: 'SecureAgents — Vlastní AI agenti pod vaší kontrolou', description: 'SecureAgents navrhuje, nasazuje a spravuje bezpečné self-hosted AI agenty pro jednotlivce a firmy v Česku.' }, '/jak-to-funguje': { title: 'Jak to funguje — SecureAgents', description: 'Zjistěte, přes jaké technologie stavíme AI agenty, kde běží data a jak řídíme náklady na provoz.' }, '/ochrana-soukromi': { title: 'Ochrana soukromí a cookies — SecureAgents', description: 'Informace o zpracování osobních údajů, cookies a analytice na webu SecureAgents.' } }; const page = pages[path] || pages['/']; const url = `https://secureagents.cz${path === '/' ? '/' : path}`; document.title = page.title; document.querySelector('meta[name="description"]')?.setAttribute('content', page.description); document.querySelector('link[rel="canonical"]')?.setAttribute('href', url); document.querySelector('meta[property="og:title"]')?.setAttribute('content', page.title); document.querySelector('meta[property="og:description"]')?.setAttribute('content', page.description); document.querySelector('meta[property="og:url"]')?.setAttribute('content', url); document.querySelector('meta[name="twitter:title"]')?.setAttribute('content', page.title); document.querySelector('meta[name="twitter:description"]')?.setAttribute('content', page.description) }, [path]) }

export default function App() { const path = usePath(); const [consent, setConsent] = useState(() => localStorage.getItem('secureagents_cookie_consent')); const [showCookies, setShowCookies] = useState(false); useRevealAnimations(path); usePageMetadata(path); const saveConsent = (value) => { localStorage.setItem('secureagents_cookie_consent', value); setConsent(value); setShowCookies(false) }; const openCookies = () => setShowCookies(true); const page = path === '/jak-to-funguje' ? <HowItWorks onOpenCookies={openCookies} /> : path === '/ochrana-soukromi' ? <PrivacyPage onOpenCookies={openCookies} /> : <HomePage onOpenCookies={openCookies} />; return <><StatusBar /><Header /><main>{page}</main><ScrollToTop />{consent === 'accepted' && <><Analytics /><SpeedInsights /></>}{(!consent || showCookies) && <CookieBanner onSave={saveConsent} />}</> }
