import { useEffect, useState } from 'react'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/react'
import { Button, ContactForm, CookieBanner, FloatingConsult, Footer, Header, Panel, ScrollToTop } from './components'
import { Link, usePath } from './router'

const PAGES = { '/jak-to-funguje': HowItWorks, '/ochrana-soukromi': PrivacyPage, '/o-nas': AboutPage, '/faq': FaqPage, '/blog': BlogPage, '/kontakt': ContactPage }

const implementace = { price: 'cena dle rozsahu', note: 'jednorázově, obvykle 2–4 týdny', desc: 'Agent se napojí na vaše nástroje, dostane jasné hranice a projde testem v reálném provozu.', items: ['Integrace do e-mailu, kalendáře, CRM či interních systémů', 'Vlastní automatizace a logika na míru', 'Nastavení přístupů, izolace dat a limitů', 'Zaškolení týmu a předání provozu'] }
const provoz = { price: 'individuální paušál', note: 'měsíčně, podle prostředí a SLA', desc: 'Dlouhodobý dohled nad provozem, úpravy a podpora, když ji tým potřebuje.', items: ['Monitoring provozu a nákladů na modely', 'Pravidelné úpravy a rozvoj agentů', 'Kritické stavy hlídá monitoring nepřetržitě', 'Běžná odborná podpora v pracovní době'] }
const process = [['01', 'Konzultace', 'Probereme prioritní procesy, očekávaný přínos a citlivost dat.'], ['02', 'Návrh', 'Připravíme architekturu, rozsah a bezpečnostní model pro vaše prostředí.'], ['03', 'Nasazení', 'Během 2–4 týdnů agenta nastavíme, propojíme s nástroji a otestujeme.'], ['04', 'Provoz', 'Zajišťujeme monitoring, úpravy, pravidelný přehled a dlouhodobý rozvoj.']]
const technology = [
  ['n8n', 'Automatizace procesů, monitoring i firemní asistent', 'Předvídatelný běh, kompletní historie všech akcí, jedna platforma pro celou firmu', 'U většiny firemních nasazení — od hlídání provozu po automatizaci procesů'],
  ['Vlastní skript', 'Výpočty a statistická detekce', 'Přesný a levný výsledek tam, kde by jazykový model jen tipoval', 'Detekce odchylek, prahové hodnoty, práce s naměřenými daty'],
  ['OpenClaw', 'Asistent dostupný z messengeru', 'Dlouhodobá paměť napříč týdny, volně formulované požadavky', 'Když chcete asistenta v Telegramu či WhatsAppu, se kterým se dá volně bavit']
]
const technologyLayerB = [
  ['Open WebUI / LibreChat', 'Plošný chatovací přístup pro zaměstnance', 'Self-hosted, firemní SSO, žádná data neputují do cizí webové appky', 'U větších firem, kde k AI potřebuje běžný přístup víc lidí napříč odděleními']
]
const infrastructure = [
  ['Doporučeno', 'Self-hosted', 'Agent běží na vašem vlastním hardwaru — firemní server nebo mini PC.', ['Data nikdy neopustí vaši síť', 'Jednorázová investice do hardwaru (pokud ho nemáte)', 'Vyžaduje minimální údržbu, kterou zajišťujeme my']],
  ['Alternativa', 'Privátní VPS', 'Agent běží na pronajatém serveru (např. v EU datacentru), pokud nemáte vlastní hardware.', ['Rychlý start bez nákupu hardwaru', 'Data u prověřeného poskytovatele v EU, mimo velké Big Tech cloudy', 'Měsíční náklad na server navíc k paušálu']],
  ['Pro specifické případy', 'Hybridní', 'Citlivá data a logika na vašem serveru, výpočetně náročné úlohy externě.', ['Kombinuje kontrolu nad daty s výkonem cloudu', 'Vyžaduje pečlivější návrh architektury', 'Typicky u větších firemních nasazení']]
]
const modelTiers = [
  ['Nejvyšší kontrola', 'Lokální model', 'Model běží přímo na hardwaru klienta, dotazy neopustí jeho síť. Vhodné tam, kde server utáhne model dostatečné kvality pro danou úlohu — cenou jsou vyšší nároky na hardware.'],
  ['Rozumný kompromis', 'Evropský poskytovatel', 'Model běží u poskytovatele v EU, data zůstávají v evropské jurisdikci, zpravidla bez trvalého uložení dotazů. Vyvážený poměr mezi kvalitou modelu a kontrolou nad daty.'],
  ['Nejvyšší kvalita', 'Globální poskytovatel s nulovou retencí', 'Nejvyšší dostupná kvalita modelu, dotazy se u poskytovatele neukládají. Vhodné tam, kde úloha potřebuje opravdu silný model a data nepatří do nejcitlivější kategorie.']
]
const scenarios = [
  ['Bezpečné napojení systémů', 'Předá jen nezbytná data mezi CRM, interními systémy a nástroji, které už ve firmě používáte.'],
  ['Provozní přehledy pro vedení', 'Propojí data z vybraných nástrojů do stručného pravidelného reportu pro tým nebo vedení, místo ručního dohledávání.'],
  ['Firemní e-mail pod kontrolou', 'Vytřídí příchozí poštu týmu, vytáhne úkoly a připraví návrhy odpovědí k vašemu schválení.'],
  ['Hlídání provozních hodnot', 'Sleduje naměřená data z firemních systémů, rozpozná odchylku od běžného stavu a upozorní odpovědnou osobu dřív, než se z toho stane problém.']
]
const monitoring = [
  ['Heartbeat a dostupnost', 'Provoz agenta hlídá self-hosted Uptime Kuma. Jakmile heartbeat vypadne, přijde nám upozornění během několika minut.'],
  ['Vytížení CPU, RAM a disku', 'Sledujeme, jestli agent nezačíná zatěžovat infrastrukturu nad rámec běžného provozu. U komplexnějších nasazení monitoring rozšiřujeme o Prometheus a Grafanu.'],
  ['Logování', 'Veškerá činnost agenta se loguje — co udělal, kdy a s jakým výsledkem, pro zpětnou kontrolu i řešení incidentů.'],
  ['Alerty', 'Uptime Kuma i vlastní skripty na sledování nákladů API hlásí výpadek, chybu nebo blížící se limit rovnou nám — bez čekání na to, až si toho někdo u vás všimne.'],
  ['Dashboard pro klienta', 'Přehled stavu a nákladů v dashboardu, který pro klienta nastavíme, místo měsíčního reportu v e-mailu.']
]
const costs = [
  ['Ke každé úloze jiný model', 'Jednoduché úlohy jdou na levnější, rychlejší model. Náročnější úlohy na výkonnější model. Výběr modelu nikdy nenecháváme na automatickém routingu bez kontroly nákladů.'],
  ['Omezené kontextové okno', 'Agent nedostává při každém dotazu celou historii všeho — jen relevantní část. Méně vstupního textu znamená méně tokenů a nižší cenu za dotaz.'],
  ['Cachování opakovaných dotazů', 'Opakované systémové instrukce se cachují místo opakovaného přepočítávání, což u některých poskytovatelů výrazně snižuje cenu.'],
  ['Limity a alerty', 'Každé nasazení má nastavený měsíční strop útraty za API, který hlídáme vlastními skripty. Při blížícím se limitu dostaneme upozornění včas.'],
  ['Měsíční přehled', 'V rámci paušálu dostanete stručný report: kolik agent za měsíc stál, na čem, a jestli se něco vymykalo obvyklému průběhu.']
]

function SectionHead({ eyebrow, title, children }) { return <div className="section-head"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{children && <p className="section-sub">{children}</p>}</div> }
function HomePage({ onOpenCookies }) { return <>
  <section className="hero no-border"><div className="wrap"><div className="eyebrow">Konfigurace a správa AI agentů</div><h1>Vlastní AI agenti,<br />které máte <em>pod kontrolou</em>.</h1><p className="lede">Navrhujeme, nasazujeme a spravujeme self-hosted AI agenty pro firmy — propojené s vašimi nástroji, bez posílání citlivých dat cizím cloudům.</p><div className="cta-row"><Button to="/kontakt" primary eventName="Kliknout na konzultaci">Nezávazná konzultace</Button><Button to="/#sluzby" eventName="Zobrazit služby">Zobrazit služby</Button></div></div></section>
  <section id="pro-koho"><div className="wrap"><SectionHead eyebrow="Pro koho" title="Firmy, kterým záleží na integritě dat" /><div className="grid-2"><div><h3>Integrace do firemních procesů</h3><p>Chcete integrovat AI agenty do chodu firmy — do e-mailu, kalendáře, CRM nebo interních systémů — ale s jasnými hranicemi a bez závislosti na cizích SaaS platformách.</p></div><div><h3>Zefektivnění práce</h3><p>Chcete, aby tým trávil méně času rutinou. Agent připraví přehledy, vytřídí poštu nebo sesbírá data z více nástrojů na jedno místo.</p></div></div></div></section>
  <section id="sluzby"><div className="wrap"><SectionHead eyebrow="Nabídka" title="Dvě položky, žádná překvapení">Cena se skládá ze vstupní implementace podle rozsahu a měsíčního paušálu za provoz — žádné skryté položky navíc.</SectionHead><Panel className="pricing"><div className="pricing-row"><div className="pricing-part"><div className="tier">Implementace</div><div className="price">{implementace.price} <small>{implementace.note}</small></div><p className="desc">{implementace.desc}</p><ul>{implementace.items.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="pricing-plus">+</div><div className="pricing-part"><div className="tier">Provoz</div><div className="price">{provoz.price} <small>{provoz.note}</small></div><p className="desc">{provoz.desc}</p><ul>{provoz.items.map((item) => <li key={item}>{item}</li>)}</ul></div></div></Panel><p className="included-note"><b>Monitoring je součástí každé služby</b> — sledujeme, že agent běží správně a náklady na API zůstávají pod kontrolou, a jednou měsíčně dostanete stručný přehled. <Link to="/jak-to-funguje#monitoring">Jak přesně monitoring funguje</Link>.</p><div className="audit"><p><b>Nejste si jistí rozsahem?</b> Začneme volitelným auditem — zmapujeme procesy, data a infrastrukturu a připravíme bezpečný plán nasazení. Od 25 000 Kč, obvykle do 2 týdnů. Pokud už agenta máte nastaveného odjinud, nabízíme i samostatný placený bezpečnostní audit.</p><Button to="/kontakt">Domluvit konzultaci</Button></div></div></section>
  <section id="proces"><div className="wrap"><SectionHead eyebrow="Jak to probíhá" title="Od konzultace po provoz" /><div className="process">{process.map(([number, title, text]) => <div className="step" key={number}><div className="num">{number}</div><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
  <section id="proc"><div className="wrap"><SectionHead eyebrow="Proč SecureAgents" title="Kontrola nad agentem zůstává na vaší straně" /><div className="why-grid">{[['Vlastní infrastruktura', 'Byznysová data a historie agenta zůstávají u vás — na vašem NAS, VPS nebo serveru. K AI modelu jde jen jednotlivý dotaz, bez trvalého uložení.'], ['Citlivé kroky čekají na schválení', 'Než agent odešle zprávu, změní záznam nebo sáhne na peníze, čeká na vaše potvrzení. Automaticky běží jen to, u čeho to dává smysl.'], ['Reálná provozní zkušenost', 'Agenty dlouhodobě provozujeme na vlastní infrastruktuře — víme, co se u nich v praxi rozbíjí a jak se tomu dá předejít.']].map(([title, text]) => <div className="why-item" key={title}><h4>{title}</h4><p>{text}</p></div>)}</div></div></section>
  <section id="scenare"><div className="wrap"><SectionHead eyebrow="Konkrétní využití" title="Kde agent ušetří čas hned po nasazení">Agent dostane přesně vymezené úkoly, nástroje a oprávnění v rámci vaší firmy — každý scénář stojí na konkrétní práci, kterou dnes někdo dělá ručně.</SectionHead><div className="scenario-grid">{scenarios.map(([title, text]) => <div className="scenario-card panel" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div><p className="model-note">Modelové scénáře ukazují typické možnosti nasazení. Konkrétní rozsah vždy navrhneme podle vašich dat a procesů.</p></div></section>
  <Footer onOpenCookies={onOpenCookies} />
</> }

function ContactPage({ onOpenCookies }) { return <>
  <section className="hero compact no-border"><div className="wrap"><div className="eyebrow">Poptávka</div><h1>Popište, co by měl <em>agent převzít</em>.</h1><p className="lede">Ozveme se zpátky s návrhem, jak dál — a domluvíme nezávaznou úvodní konzultaci.</p></div></section>
  <section><div className="wrap contact-wrap"><ContactForm /></div></section>
  <Footer onOpenCookies={onOpenCookies} />
</> }

function HowItWorks({ onOpenCookies }) { return <>
  <section className="hero compact no-border"><div className="wrap"><div className="eyebrow">Pod pokličkou</div><h1>Přes co to stavíme a <em>co vás to bude stát.</em></h1><p className="lede">Žádná černá skříňka. Tady je popsané, jaký software agenty pohání, kde reálně běží data a jak se řídí náklady na provoz.</p></div></section>
  <section id="technologie"><div className="wrap"><SectionHead eyebrow="01 · Technologie" title="Čím agenty stavíme">Rozlišujeme dvě vrstvy nasazení: nástroje, které pohánějí konkrétní automatizované procesy, a nástroje, přes které mají zaměstnanci plošný přístup k AI. Ve firmách primárně stavíme na n8n — jedna platforma zvládne monitoring, automatizaci i chat s asistentem.</SectionHead><div className="stack-grid"><div className="head" /><div className="head mono">ÚČEL</div><div className="head mono">SILNÁ STRÁNKA</div><div className="head mono">KDY TO NASAZUJEME</div><div className="stack-group">Vrstva A · Automatizace procesů</div>{technology.flatMap(([name, purpose, strength, when], index) => [<div key={`${name}-name`}><div className={`tool ${index === 0 ? 'primary' : ''}`}>{name}</div>{index === 0 && <span className="tag-default">Výchozí volba</span>}</div>, <div key={`${name}-purpose`} className="role">{purpose}</div>, <div key={`${name}-strength`} className="role">{strength}</div>, <div key={`${name}-when`} className="role">{when}</div>])}<div className="stack-group">Vrstva B · Plošný přístup k AI</div>{technologyLayerB.flatMap(([name, purpose, strength, when]) => [<div key={`${name}-name`}><div className="tool">{name}</div></div>, <div key={`${name}-purpose`} className="role">{purpose}</div>, <div key={`${name}-strength`} className="role">{strength}</div>, <div key={`${name}-when`} className="role">{when}</div>])}</div><div className="callout"><b>Někdy je správná odpověď „tohle AI nepotřebuje“.</b> Na hlídání naměřených hodnot nebo výpočty stačí obyčejný skript — je levnější, přesnější a dá se ověřit. Jazykový model nasazujeme až tam, kde skutečně přidá hodnotu.</div></div></section>
  <section id="infrastruktura"><div className="wrap"><SectionHead eyebrow="02 · Infrastruktura" title="Kde to celé běží">Doporučujeme self-hosted řešení, protože dává nejvyšší kontrolu nad daty. Podle rozpočtu a technického zázemí jde postavit i jinak — byznysová data, historie a logika agenta ale vždy zůstávají na infrastruktuře, kterou pro vás navrhneme.</SectionHead><div className="infra-grid">{infrastructure.map(([tier, title, text, items], index) => <Panel key={title} className={`infra-card ${index === 0 ? 'recommended' : ''}`}><div className="tier">{tier}</div><h3>{title}</h3><p>{text}</p><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></Panel>)}</div><p className="callout"><b>Pro větší a citlivější nasazení</b> agenta nestavíme jako jeden univerzální systém s přístupem ke všemu — rozdělujeme ho podle domény dat (e-mail, CRM, finance…), takže případný problém v jedné oblasti neohrozí zbytek.</p></div></section>
  <section id="volba-modelu"><div className="wrap"><SectionHead eyebrow="03 · Volba modelu" title="Kde běží samotný AI model">Volba modelu se neřídí tím, co je obecně bezpečnější, ale tím, jakou kvalitu daná úloha potřebuje a jak citlivá data jí protečou.</SectionHead><div className="infra-grid">{modelTiers.map(([tier, title, text]) => <Panel key={title} className="infra-card"><div className="tier">{tier}</div><h3>{title}</h3><p>{text}</p></Panel>)}</div><p className="callout"><b>Konkrétní úroveň volíme případ od případu</b> — podle typu dat a úlohy, klidně různou pro různé procesy v rámci jedné firmy.</p></div></section>
  <section id="monitoring"><div className="wrap"><SectionHead eyebrow="04 · Monitoring" title="Jak hlídáme, že agent běží, jak má">Monitoring běží nepřetržitě na pozadí.</SectionHead><div className="cost-flow">{monitoring.map(([title, text], index) => <div className="cost-row" key={title}><div className="marker">{String(index + 1).padStart(2, '0')}</div><div><h4>{title}</h4><p>{text}</p></div></div>)}</div></div></section>
  <section id="naklady"><div className="wrap"><SectionHead eyebrow="05 · Náklady na tokeny" title="Jak se platí AI model a jak náklady držíme dole">Každý dotaz na AI model stojí peníze podle množství zpracovaného textu — tzv. tokenů. Takhle to řídíme:</SectionHead><div className="cost-flow">{costs.map(([title, text], index) => <div className="cost-row" key={title}><div className="marker">{String(index + 1).padStart(2, '0')}</div><div><h4>{title}</h4><p>{text}</p></div></div>)}</div><div className="callout"><b>Náklady řešíme už při návrhu.</b> Strop útraty, volbu modelu i velikost kontextového okna ladíme při stavbě agenta, aby se provoz nevymkl hned první měsíc.</div></div></section>
  <Footer technical onOpenCookies={onOpenCookies} />
</> }

function PrivacyPage({ onOpenCookies }) { return <><section className="hero compact no-border"><div className="wrap"><div className="eyebrow">Soukromí</div><h1>Ochrana osobních údajů a <em>cookies</em>.</h1><p className="lede">Přehledně vysvětlujeme, jak na webu SecureAgents pracujeme s údaji návštěvníků.</p></div></section><section><div className="wrap privacy-page"><div className="privacy-card"><h2>Správce údajů</h2><p>Správcem osobních údajů je Adam Pospíšek, projekt SecureAgents. Pro dotazy k soukromí nás kontaktujte na <a href="mailto:info@secureagents.cz">info@secureagents.cz</a>.</p></div><div className="privacy-card"><h2>Jaké údaje zpracováváme</h2><p>Pokud vyplníte kontaktní formulář, odešleme uvedené údaje (jméno, e-mail, firma, obsah zprávy) prostřednictvím e-mailové služby Resend na náš firemní e-mail, kde je zpracujeme pouze pro vyřízení vašeho dotazu a navazující komunikaci. Formulář sám o sobě data na webu neukládá. Pokud nám místo toho napíšete přímo e-mail, platí totéž.</p></div><div className="privacy-card"><h2>Cookies a místní úložiště</h2><p>Web si do místního úložiště prohlížeče ukládá vaši volbu ohledně analytiky. Tato nezbytná položka se jmenuje <code>secureagents_cookie_consent</code> a slouží pouze k tomu, aby se lišta nezobrazovala při každé návštěvě.</p><p>Analytická měření Vercel Analytics a Speed Insights spouštíme až po vašem souhlasu. Pomáhají nám sledovat návštěvnost a technický výkon webu.</p><button className="btn" onClick={onOpenCookies}>Změnit nastavení cookies</button></div><div className="privacy-card"><h2>Vaše práva</h2><p>Máte právo požádat o přístup k osobním údajům, jejich opravu, výmaz, omezení zpracování nebo vznést námitku. Žádost pošlete na výše uvedený e-mail.</p><p>Pokud se domníváte, že s údaji nenakládáme správně, můžete se obrátit na Úřad pro ochranu osobních údajů.</p></div><div className="privacy-card"><h2>Aktualizace zásad</h2><p>Tyto zásady můžeme upravit, pokud se změní způsob fungování webu nebo používané služby. Poslední aktualizace: 9. srpna 2026.</p></div></div></section><Footer onOpenCookies={onOpenCookies} /></> }

const principles = [
  ['Nejdřív mapa, pak přístup', 'Než agenta k čemukoliv připojíme, zmapujeme datové toky, oprávnění a rizika. Návrh integrace vzniká až na základě tohoto přehledu.'],
  ['Testujeme v izolaci', 'Nové automatizace nejdřív běží v testovacím prostředí na omezených datech. Do ostrého provozu je pouštíme, až když se chovají podle očekávání.'],
  ['Máte do toho vidět', 'Víte přesně, jaký model se používá, kde běží a kolik vás který agent aktuálně stojí.'],
  ['Bezpečnost nekončí spuštěním', 'Provoz průběžně sledujeme, upravujeme oprávnění podle toho, co agent reálně potřebuje, a na nová rizika vás upozorníme sami.']
]
function AboutPage({ onOpenCookies }) { return <>
  <section className="hero compact no-border"><div className="wrap"><div className="eyebrow">O nás</div><h1>Bezpečnost bereme <em>vážně</em>.</h1><p className="lede">SecureAgents stojí na jednoduché myšlence: AI agenty má ve firmě smysl nasazovat jen tehdy, když víte, kam jdou vaše data a kdo k nim má přístup.</p></div></section>
  <section id="pristup"><div className="wrap content-page"><SectionHead eyebrow="01 · Přístup" title="Proč je pro nás bezpečnost na prvním místě" /><p>Za SecureAgents stojí zkušenost z kyberbezpečnosti — z prostředí, kde se u každé nové technologie nejdřív ptáme, co se na ní dá pokazit a zneužít. Se stejným pohledem přistupujeme k AI agentům. Než agent dostane přístup k e-mailu, kalendáři nebo CRM, projdeme, jaká data uvidí, co s nimi smí udělat a co se stane, když se něco pokazí.</p><p>Většina nabídek na trhu se soustředí na to, co všechno agent zvládne. Nás stejně tak zajímá, kde má mít hranice — jaká data neuvidí, co nesmí odeslat sám a kde se musí zeptat. Nasazení tím trvá o něco déle, ale výsledek pak jde ve firmě používat bez obav, kam vaše data doputují.</p></div></section>
  <section id="metodika"><div className="wrap"><SectionHead eyebrow="02 · Jak pracujeme" title="Zásady, kterých se držíme u každého nasazení" /><div className="cost-flow">{principles.map(([title, text], index) => <div className="cost-row" key={title}><div className="marker">{String(index + 1).padStart(2, '0')}</div><div><h4>{title}</h4><p>{text}</p></div></div>)}</div></div></section>
  <Footer onOpenCookies={onOpenCookies} />
</> }

const faqs = [
  ['Kolik AI agent stojí?', 'Cena se skládá ze vstupní implementace a měsíčního paušálu. Audit a návrh začíná na 25 000 Kč, nasazení se cení podle rozsahu a provoz má individuální paušál podle prostředí a SLA — víc v sekci Nabídka na hlavní stránce.'],
  ['Musíme mít vlastní server?', 'Ne. Doporučujeme self-hosted řešení na vašem hardwaru, ale pokud ho nemáte, agent může běžet na privátní VPS u prověřeného EU poskytovatele, případně v hybridním modelu.'],
  ['Jak dlouho nasazení trvá?', 'Samotné nasazení agenta typicky trvá 2–4 týdny od zahájení po předání do provozu, podle rozsahu integrace.'],
  ['Kam chodí naše data?', 'Data, historie a logika agenta zůstávají na infrastruktuře, kterou pro vás navrhneme. K poskytovateli AI modelu putuje vždy jen konkrétní dotaz — trvalý přístup do vašich systémů nedostane.'],
  ['Co když nemáme vlastní IT tým?', 'Nevadí. Agenta při implementaci nastavíme a propojíme za vás a v rámci paušálu se pak staráme o dohled, úpravy i podporu.'],
  ['Jak se hlídají náklady na AI model?', 'Podle úlohy volíme odpovídající, ne automaticky nejdražší model, omezujeme, kolik textu se posílá do každého dotazu, a opakující se dotazy se neúčtují dvakrát. Každé nasazení navíc má měsíční strop útraty s upozorněním, a jednou měsíčně vidíte souhrn za uplynulé období.'],
  ['Můžeme začít v menším rozsahu a pak rozšířit?', 'Ano. Obvykle začínáme auditem a návrhem, který určí prioritní procesy, a nasazení pak rozšiřujeme postupně podle toho, co se osvědčí.'],
  ['Nabízíte bezpečnostní audit i bez nasazení agenta?', 'Ano. Pokud už agenta máte nastaveného od jiného dodavatele nebo interně, nabízíme samostatný placený bezpečnostní audit.'],
  ['Jak rychle reaguje podpora?', 'V rámci paušálu máte běžnou odbornou podporu v pracovní době. Kritické stavy navíc nepřetržitě hlídá náš monitorovací systém a upozorní nás, jakmile něco vybočí z normálu.'],
  ['Jaké nástroje a frameworky používáte?', 'Ve firmách primárně stavíme na n8n — zvládne monitoring, automatizaci procesů i chat s asistentem v jedné platformě. Pro výpočty a statistickou detekci píšeme vlastní skripty, pro asistenty v messengeru sáhneme po OpenClaw — víc na stránce Jak to funguje.'],
  ['Řešíte i soulad s legislativou, jako je AI Act?', 'Ano. Nasazení navrhujeme tak, aby odpovídalo požadavkům na lidský dohled, logování a informovanost zaměstnanců podle AI Actu — bez ohledu na to, že termín pro vysoce rizikové systémy byl mezitím odložen na prosinec 2027. Víc o tom, co AI Act reálně znamená pro menší firmy, píšeme na blogu.']
]
function FaqItem({ q, a }) { const [open, setOpen] = useState(false); return <div className="faq-item"><button className="faq-q" onClick={() => setOpen((value) => !value)} aria-expanded={open}>{q}<span className="faq-icon">{open ? '−' : '+'}</span></button>{open && <p className="faq-a">{a}</p>}</div> }
function FaqPage({ onOpenCookies }) { return <>
  <section className="hero compact no-border"><div className="wrap"><div className="eyebrow">Časté dotazy</div><h1>Otázky, které <em>slýcháme nejčastěji</em>.</h1><p className="lede">Pokud tu nenajdete odpověď na svou otázku, napište nám — rádi ji probereme na nezávazné konzultaci.</p></div></section>
  <section><div className="wrap content-page">{faqs.map(([q, a]) => <FaqItem key={q} q={q} a={a} />)}</div></section>
  <Footer onOpenCookies={onOpenCookies} />
</> }

const posts = [
  ['Co pro vaši firmu znamená AI Act — a co ne', 'Září 2026', 'Když se řekne AI Act, většina firem si představí buď paniku, nebo že se jich to netýká. Realita je střízlivější a stojí za to ji znát, než začnete AI ve firmě používat.\n\nEvropský zákon o umělé inteligenci není jeden pevný termín, po kterém najednou platí všechno. Zavádí se postupně a část harmonogramu se navíc letos v červenci posunula — takzvaný Digital Omnibus odložil povinnosti pro takzvané vysoce rizikové systémy z srpna 2026 na prosinec 2027. Pokud jste tedy nedávno četli, že „od srpna 2026 platí přísná pravidla pro AI“, je to už neaktuální.\n\nCo naopak platí už teď a nebylo odloženo, je povinnost takzvané AI gramotnosti — firmy musí zajistit, aby lidé, kteří s AI pracují, rozuměli tomu, co dělá a jaká má omezení. Tahle povinnost běží od února 2025, tedy déle než rok, a řada firem o ní vůbec neví.\n\nDruhá věc, kterou je dobré znát dřív, než si AI necháte nasadit: zákon rozlišuje mezi tím, kdo systém postaví, a tím, kdo ho používá. Jako firma, která si nechá agenta implementovat, jste v roli uživatele s vlastními povinnostmi — mimo jiné informovat zaměstnance, kterých se nasazení týká, a zajistit, že nad systémem existuje reálný lidský dohled, ne jen automatické „ano“ na všechno, co AI navrhne. Vysoce rizikové kategorie, kam patří například hodnocení zaměstnanců nebo rozhodování o lidech, mají přísnější požadavky — ale i tady platí odklad do prosince 2027, ne srpen 2026.\n\nPro naprostou většinu firemních nasazení, se kterými se setkáváme — automatizace procesů, hlídání provozních dat, interní asistenti — jde o běžný software, ne o vysoce rizikový systém. Přesto do každého návrhu zahrnujeme prvky, které s AI Actem přímo souvisí: zaškolení týmu, které zároveň plní požadavek na AI gramotnost, historii běhů jako doklad monitoringu, a krok lidského schválení tam, kde agent dělá něco citlivého. Dělali bychom to takhle i bez zákona za zády.\n\nTento text je zjednodušený přehled, ne právní poradenství. Legislativa se v této oblasti stále vyvíjí — pro konkrétní situaci ve vaší firmě doporučujeme konzultaci s právníkem. Naposledy aktualizováno: září 2026.'],
  ['Proč self-hosted AI agent není jen módní heslo', 'Srpen 2026', 'Naprostá většina AI nástrojů na trhu funguje jako SaaS — vaše data putují na servery třetí strany a vy věříte, že s nimi bude naloženo podle smluvních podmínek, které se navíc mohou kdykoliv změnit. U firemních procesů, kde figurují e-maily, smlouvy nebo zákaznická data, je to riziko, které se dá poměrně snadno obejít.\n\nSelf-hosted agent běží na vašem hardwaru nebo na privátním serveru, který si pronajmete vy. Historie konverzací, přístupová oprávnění a logika automatizací zůstávají u vás — k externímu poskytovateli AI modelu putuje jen samotný dotaz, žádný průběžný přístup k datům. O přístupu k datům tak nakonec rozhodujete vy sami — bez ohledu na to, jak si někdo jiný zrovna upraví smluvní podmínky.\n\nCena za tuto kontrolu je vyšší nárok na počáteční návrh. Architekturu, oprávnění a izolaci dat je potřeba promyslet předem — po incidentu už se to dělá podstatně hůř.'],
  ['Tři oprávnění, která bychom AI agentovi nedali bez rozmyslu', 'Srpen 2026', 'Nadšení z toho, co všechno agent dokáže automatizovat, snadno vede k tomu, že dostane širší přístup, než reálně potřebuje. Tři oprávnění, u kterých se vždy zastavíme a ptáme se, jestli jsou opravdu nutná:\n\nOdesílání e-mailů bez schválení. Agent, který sám odpovídá klientům nebo partnerům, může snadno poslat něco, co jste neschválili. U komunikace navenek je návrh odpovědi k vašemu schválení bezpečnější výchozí nastavení než automatické odeslání.\n\nPřístup k platbám nebo fakturaci. Automatizace plateb je lákavá, ale chyba v logice nebo v datech se tu okamžitě promítne do peněz. Tahle oprávnění dáváme jen tam, kde je vidět jasná kontrola a schvalovací krok.\n\nŠiroký přístup k celému úložišti místo konkrétní složky. Je jednodušší dát agentovi přístup ke všemu než k tomu vybírat, ale rozsah oprávnění má odpovídat konkrétnímu úkolu, který agent dělá dnes. Co bude potřeba za půl roku, se dá přidat, až to bude potřeba.'],
  ['Jak se počítá cena za AI model a proč faktura kolísá', 'Srpen 2026', 'Každý dotaz na AI model stojí peníze podle množství zpracovaného textu — takzvaných tokenů. Čím delší vstup (historie konverzace, přiložené dokumenty, systémové instrukce) a čím delší odpověď, tím vyšší cena za jeden dotaz. Proto může měsíční faktura kolísat i při zdánlivě stejném objemu práce.\n\nNáklady držíme dole několika způsoby: jednoduché úlohy jdou na levnější a rychlejší model, náročnější až na výkonnější model; agent nedostává při každém dotazu celou historii, jen relevantní část; opakované systémové instrukce se cachují místo opakovaného přepočítávání.\n\nKe každému nasazení nastavujeme měsíční strop útraty za API s alertem před jeho dosažením. Jednou měsíčně pak posíláme přehled, ze kterého je vidět, kam peníze šly a proč se částka případně změnila oproti minulému měsíci.']
]
function BlogPage({ onOpenCookies }) { return <>
  <section className="hero compact no-border"><div className="wrap"><div className="eyebrow">Blog</div><h1>Poznámky z <em>provozu AI agentů</em>.</h1><p className="lede">Krátké texty o bezpečném nasazení, self-hostingu a řízení nákladů — z toho, co reálně řešíme u zákazníků.</p></div></section>
  <section><div className="wrap content-page">{posts.map(([title, date, body]) => <article className="blog-post" key={title}><span className="blog-tag">{date}</span><h2>{title}</h2>{body.split('\n\n').map((paragraph, index) => <p key={index}>{paragraph}</p>)}</article>)}</div></section>
  <Footer onOpenCookies={onOpenCookies} />
</> }

function useRevealAnimations(path) { useEffect(() => { const targets = [...document.querySelectorAll('.hero .wrap, .section-head, .grid-2, .panel, .step, .why-item, .callout, .audit, footer .wrap, .privacy-card, .cost-row, .faq-item, .blog-post')]; const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches; targets.forEach((element) => element.classList.add('reveal')); if (reduced) { targets.forEach((element) => element.classList.add('is-visible')); return undefined } document.documentElement.classList.add('motion-ready'); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target) } }), { threshold: 0.12 }); targets.forEach((element) => observer.observe(element)); return () => { observer.disconnect(); document.documentElement.classList.remove('motion-ready') } }, [path]) }

function usePageMetadata(path) { useEffect(() => { const pages = { '/': { title: 'SecureAgents — Vlastní AI agenti pod vaší kontrolou', description: 'SecureAgents navrhuje, nasazuje a spravuje bezpečné self-hosted AI agenty pro firmy v Česku.' }, '/jak-to-funguje': { title: 'Jak to funguje — SecureAgents', description: 'Zjistěte, přes jaké technologie stavíme AI agenty, kde běží data a jak řídíme náklady na provoz.' }, '/o-nas': { title: 'O nás — SecureAgents', description: 'Proč je pro nás bezpečnost na prvním místě a jak vypadá spolupráce na nasazení AI agenta ve vaší firmě.' }, '/faq': { title: 'Časté dotazy — SecureAgents', description: 'Odpovědi na nejčastější otázky k nasazení, cenám, datům a provozu AI agentů od SecureAgents.' }, '/blog': { title: 'Blog — SecureAgents', description: 'Články o bezpečném nasazení AI agentů, self-hostingu a řízení nákladů na AI modely.' }, '/kontakt': { title: 'Kontakt — SecureAgents', description: 'Popište, co by měl AI agent ve vaší firmě převzít, a domluvte si bezplatnou úvodní konzultaci.' }, '/ochrana-soukromi': { title: 'Ochrana soukromí a cookies — SecureAgents', description: 'Informace o zpracování osobních údajů, cookies a analytice na webu SecureAgents.' } }; const page = pages[path] || pages['/']; const url = `https://secureagents.cz${path === '/' ? '/' : path}`; document.title = page.title; document.querySelector('meta[name="description"]')?.setAttribute('content', page.description); document.querySelector('link[rel="canonical"]')?.setAttribute('href', url); document.querySelector('meta[property="og:title"]')?.setAttribute('content', page.title); document.querySelector('meta[property="og:description"]')?.setAttribute('content', page.description); document.querySelector('meta[property="og:url"]')?.setAttribute('content', url); document.querySelector('meta[name="twitter:title"]')?.setAttribute('content', page.title); document.querySelector('meta[name="twitter:description"]')?.setAttribute('content', page.description) }, [path]) }

export default function App() { const path = usePath(); const [consent, setConsent] = useState(() => localStorage.getItem('secureagents_cookie_consent')); const [showCookies, setShowCookies] = useState(false); useRevealAnimations(path); usePageMetadata(path); const saveConsent = (value) => { localStorage.setItem('secureagents_cookie_consent', value); setConsent(value); setShowCookies(false) }; const openCookies = () => setShowCookies(true); const PageComponent = PAGES[path] || HomePage; const page = <PageComponent onOpenCookies={openCookies} />; const cookieBannerVisible = !consent || showCookies; return <><Header /><main>{page}</main><ScrollToTop hidden={cookieBannerVisible} /><FloatingConsult hidden={cookieBannerVisible} />{consent === 'accepted' && <><Analytics /><SpeedInsights /></>}{cookieBannerVisible && <CookieBanner onSave={saveConsent} />}</> }
